/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Stats = IDL.Record({
  'cyclesConsumed' : IDL.Nat,
  'circulatingSupply' : IDL.Float64,
  'totalSupply' : IDL.Float64,
  'txCount' : IDL.Nat,
  'holders' : IDL.Nat,
});
export const Token = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'walletAddr' : IDL.Text,
  'network' : IDL.Text,
  'toAddr' : IDL.Text,
  'tokenSymbol' : IDL.Text,
  'fromAddr' : IDL.Text,
  'timestamp' : IDL.Int,
  'txType' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getBridgeFee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Float64, IDL.Nat],
      ['query'],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTokenPrices' : IDL.Func([], [IDL.Vec(Token)], ['query']),
  'getTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
  'recordTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Stats = IDL.Record({
    'cyclesConsumed' : IDL.Nat,
    'circulatingSupply' : IDL.Float64,
    'totalSupply' : IDL.Float64,
    'txCount' : IDL.Nat,
    'holders' : IDL.Nat,
  });
  const Token = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'walletAddr' : IDL.Text,
    'network' : IDL.Text,
    'toAddr' : IDL.Text,
    'tokenSymbol' : IDL.Text,
    'fromAddr' : IDL.Text,
    'timestamp' : IDL.Int,
    'txType' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'getBridgeFee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Float64, IDL.Nat],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTokenPrices' : IDL.Func([], [IDL.Vec(Token)], ['query']),
    'getTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
    'recordTransaction' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };